---
language: node_js
node_js:
  - "10"

sudo: false
dist: xenial

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
    - APP=packages/react-app
    - CLI=packages/react-cli
    - ADDON_GENERATORS=packages/react-generators

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH


matrix:
  include:
    - env:
      - PROJECT=$APP
    - env:
      - PROJECT=$CLI
    - env:
      - PROJECT=$ADDON_GENERATORS

before_install:
  - echo "Project: $PROJECT"

install:
  - cd $PROJECT && yarn install --non-interactive

jobs:
  fail_fast: true

  include:
    - stage: "Quality"
      name: "Lint JS/TS"
      script: cd $PROJECT && yarn lint:js

    - stage: "App Generation Smoke Test"
      script: echo "Need non-interactive mode"
      env: ISOLATED=true
