---
language: node_js
node_js:
  - "10"

sudo: false
dist: xenial

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
    - APP=packages/react-app
    - CLI=packages/react-cli
    - ADDON_GENERATORS=packages/react-generators

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH


lint: &lint
  script:
    - echo "Project: $PROJECT"
    - cd $PROJECT && yarn install --non-interactive
    - cd $PROJECT && yarn lint:js


jobs:
  fail_fast: true

  include:
    - stage: "Quality"
      <<: *lint
      name: "Lint JS/TS (app)"
      env:
      - PROJECT=$APP

    - name: "Lint JS/TS (cli)"
      <<: *lint
      env:
      - PROJECT=$CLI
      - PROJECT=$ADDON_GENERATORS

    - name: "Lint JS/TS (generators)"
      <<: *lint
      env:
      - PROJECT=$ADDON_GENERATORS

    - stage: "App Generation Smoke Test"
      script: echo "Need non-interactive mode"
      env: ISOLATED=true
