#!/bin/bash

if [ -z "$REACT_CLI_PATH" ]; then
  echo '$REACT_CLI_PATH is not set!'
  echo '$REACT_CLI_PATH must point to wherever you cloned the react-cli project.'
  exit 1
fi

# if [[ $PATH != *"$(yarn global bin)"* ]]; then 
#   echo "yarn's bin folder is not in the PATH"
#   echo "add '$(yarn global bin)' to the path"
#   echo ""
#   echo "export PATH=\"\$PATH:\$(yarn global bin)\""
#   exit 1
# fi

function react-cli {
  # First arg
  given_command=$1
  # The rest of the args
  arguments=${@:2}

  case $given_command in
    new) 
      # TODO: ensure ember is installed globally
      #       (npx re-installs every time)
      ( cd $REACT_CLI_PATH/blueprints/react-app && yarn ) \
      && \
      npx ember-cli new $arguments \
            --blueprint $REACT_CLI_PATH/blueprints/react-app \
            --yarn \
            --skip-git 
    ;;

    *) print_help;;
  esac
}

function print_help {
  echo ""
  echo "Available Commands:"
  echo ""
  echo "new                creates a new app, given options"
  echo "  examples:"
  echo "     ./react-cli new MyProject --directory ~/Development/MyProject --auth0 --jsonapi"
  echo "     ./react-cli new MyProject --jsonapi --redux"
  echo ""
  echo "  available flags:"
  echo "    --directory"
  echo "    --auth0"
  echo "    --i18n"
  echo "    --jsonapi"
  echo "    --dotnetBackend"
  echo "    --materialUi"
  echo "    --redux"
 
}

if [ $1 ]; then
  react-cli $*
else
  print_help
fi
